---
version: 0.3.0
slug: vlc
name: VLC-instance2
description: Turn your device into a Media Player with VLC
url: https://github.com/Arcanidus/addons
arch:
  - amd64
  - i386
  - armv7
  - aarch64
audio: true
discovery:
  - vlc_telnet
homeassistant: 2021.3.0.dev20210216
image: homeassistant/{arch}-addon-vlc
ingress: true
init: false
map:
  - share:ro
  - media:ro
options: {}
panel_icon: mdi:vlc
schema: false
stage: stable
startup: services
